[package]
name = "fun-images"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
csscolorparser = "0.7.2"
image = "0.25.7"
imageproc = "0.25.0"
primal = "0.3.3"
